# FFM 训练配置
training:
  # 训练参数
  lr: 0.0001
  batch_size: 1
  epochs: 200
  patch_size: false

  # 数据路径
  train_dir: "C:\Users\pytorch\Desktop\Dataset\dataset\test_train"
  val_dir: "C:\Users\pytorch\Desktop\Dataset\dataset\test_val"

  # 模型保存
  model_save_dir: "./saved/models"
  model_save_name: "flow_matching_model"

  # 验证设置
  val_frequency: 5  # 前100个epoch每5个epoch验证一次
  val_frequency_after_100: 10  # 100个epoch后每10个epoch验证一次
  save_frequency: 20  # 每20个epoch保存一次模型

inference:
  # 推理参数
  ode_steps: 50
  ode_method: "euler"
  ode_rtol: 1e-4
  ode_atol: 1e-5
  ode_step_size: 0.02

  # 测试路径
  test_model_path: "/saved/models/flow_matching_model_final.pth"
  test_lq_dir: "/media/D/ym/dataset/test/lq"
  test_output_dir: "saved/output"

data:
  # 数据预处理
  transform:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

  # DataLoader 配置
  dataloader:
    num_workers: 1
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 1
    drop_last: true

device:
  # 设备配置
  cudnn_benchmark: true
  seed: 42

comet_ml:
  # Comet ML 配置（可选）
  api_key: "eEDOoiwzjF6OMzqh4LcGkCCUj"
  project_name: "Flow Matching"
  enabled: true